import { Team } from './team';

export const TEAMS: Team[] = [
	{"teamId":"SF","teamLoc":"San Francisco","Team":"49ers","image":"/assets/images/teams/SF.png"},
	{"teamId":"CHI","teamLoc":"Chicago","Team":"Bears","image":"/assets/images/teams/CHI.png"},
	{"teamId":"CIN","teamLoc":"Cincinatti","Team":"Bengals","image":"/assets/images/teams/CIN.png"},
	{"teamId":"BUF","teamLoc":"Buffalo","Team":"Bills","image":"/assets/images/teams/BUF.png"},
	{"teamId":"DEN","teamLoc":"Denver","Team":"Broncos","image":"/assets/images/teams/DEN.png"},
	{"teamId":"CLE","teamLoc":"Cleveland","Team":"Browns","image":"/assets/images/teams/CLE.png"},
	{"teamId":"TB","teamLoc":"Tampa Bay","Team":"Buccaneers","image":"/assets/images/teams/TB.png"},
	{"teamId":"ARI","teamLoc":"Arizona","Team":"Cardinals","image":"/assets/images/teams/ARI.png"},
	{"teamId":"LAC","teamLoc":"Los Angeles","Team":"Chargers","image":"/assets/images/teams/LAC.png"},
	{"teamId":"SD","teamLoc":"San Diego","Team":"Chargers","image":"/assets/images/teams/LAC.png"},
	{"teamId":"KC","teamLoc":"Kansas City","Team":"Chiefs","image":"/assets/images/teams/KC.png"},
	{"teamId":"IND","teamLoc":"Indianapolis","Team":"Colts","image":"/assets/images/teams/IND.png"},
	{"teamId":"DAL","teamLoc":"Dallas","Team":"Cowboys","image":"/assets/images/teams/DAL.png"},
	{"teamId":"MIA","teamLoc":"Miami","Team":"Dolphins","image":"/assets/images/teams/MIA.png"},
	{"teamId":"PHI","teamLoc":"Philadelphia","Team":"Eagles","image":"/assets/images/teams/PHI.png"},
	{"teamId":"ATL","teamLoc":"Atlanta","Team":"Falcons","image":"/assets/images/teams/ATL.png"},
	{"teamId":"NYG","teamLoc":"New York","Team":"Giants","image":"/assets/images/teams/NYG.png"},
	{"teamId":"JAX","teamLoc":"Jacksonville","Team":"Jaguars","image":"/assets/images/teams/JAX.png"},
	{"teamId":"NYJ","teamLoc":"New York","Team":"Jets","image":"/assets/images/teams/NYJ.png"},
	{"teamId":"DET","teamLoc":"Detroit","Team":"Lions","image":"/assets/images/teams/DET.png"},
	{"teamId":"GB","teamLoc":"Green Bay","Team":"Packers","image":"/assets/images/teams/GB.png"},
	{"teamId":"CAR","teamLoc":"Carolina","Team":"Panthers","image":"/assets/images/teams/CAR.png"},
	{"teamId":"NE","teamLoc":"New England","Team":"Patriots","image":"/assets/images/teams/NE.png"},
	{"teamId":"OAK","teamLoc":"Oakland","Team":"Raiders","image":"/assets/images/teams/OAK.png"},
	{"teamId":"LV","teamLoc":"Las Vegas","Team":"Raiders","image":"/assets/images/teams/OAK.png"},
	{"teamId":"LAR","teamLoc":"Los Angeles","Team":"Rams","image":"/assets/images/teams/LA.png"},
	{"teamId":"STL","teamLoc":"St. Louis","Team":"Rams","image":"/assets/images/teams/LA.png"},
	{"teamId":"BAL","teamLoc":"Baltimore","Team":"Ravens","image":"/assets/images/teams/BAL.png"},
	{"teamId":"WAS","teamLoc":"Washington","Team":"Redskins","image":"/assets/images/teams/WAS.png"},
	{"teamId":"WSH","teamLoc":"Washington","Team":"Football Team","image":"/assets/images/teams/WAS.png"},
	{"teamId":"NO","teamLoc":"New Orleans","Team":"Saints","image":"/assets/images/teams/NO.png"},
	{"teamId":"SEA","teamLoc":"Seattle","Team":"Seahawks","image":"/assets/images/teams/SEA.png"},
	{"teamId":"PIT","teamLoc":"Pittsburgh","Team":"Steelers","image":"/assets/images/teams/PIT.png"},
	{"teamId":"HOU","teamLoc":"Houston","Team":"Texans","image":"/assets/images/teams/HOU.png"},
	{"teamId":"TEN","teamLoc":"Tennessee","Team":"Titans","image":"/assets/images/teams/TEN.png"},
	{"teamId":"MIN","teamLoc":"Minnesota","Team":"Vikings","image":"/assets/images/teams/MIN.png"},
]